-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 02, 2022 at 08:44 PM
-- Server version: 8.0.30-0ubuntu0.22.04.1
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `epiz_29692570_alnitakdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `constellations`
--

CREATE TABLE `constellations` (
  `id` int NOT NULL,
  `nombre` varchar(200) NOT NULL,
  `info` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `constellations`
--

INSERT INTO `constellations` (`id`, `nombre`, `info`) VALUES
(1, 'Cygnus', 'Cygnus is a constellation in the northern hemisphere that runs through the Milky Way. The arrangement of its main stars makes it sometimes known as the Northern Cross, in contrast to the southern constellation of the Southern Cross.');

-- --------------------------------------------------------

--
-- Table structure for table `stars`
--

CREATE TABLE `stars` (
  `id` int NOT NULL,
  `nombre` varchar(200) DEFAULT NULL,
  `x` int NOT NULL,
  `y` int NOT NULL,
  `size` int NOT NULL,
  `idConstellation` int DEFAULT NULL,
  `starDate` date NOT NULL,
  `info` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `stars`
--

INSERT INTO `stars` (`id`, `nombre`, `x`, `y`, `size`, `idConstellation`, `starDate`, `info`) VALUES
(112, 'HD123,V=5.96,G5V,', 2755, 706, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br>'),
(113, 'HD432,V=2.27,F2III-IV,Bet Cas ', 2786, 809, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br>'),
(114, 'HD432,V=2.27,F2III-IV,Bet Cas ', 2786, 809, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br>'),
(115, 'HD761,V=0.00,, ', 2965, 88, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br>'),
(116, 'HD2083,V=0.00,, ', 2648, 2544, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br>'),
(117, 'HD2905,V=4.16,B1Ia,Kap Cas ', 3061, 1401, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br>'),
(118, 'HD2905,V=4.16,B1Ia,Kap Cas ', 3061, 1401, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(119, 'HD5394,V=2.47,B0IVe,Gam Cas ', 3502, 1226, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(120, 'HD5394,V=2.47,B0IVe,Gam Cas ', 3502, 1226, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(121, 'HD209975,V=5.11,O9.5Ib,19 Cep ', 772, 1349, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(122, 'HD211029,V=5.79,M3IIIab,', 917, 1450, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(123, 'HD211336,V=4.19,F0IV,Eps Cep ', 741, 617, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(124, 'HD211336,V=4.19,F0IV,Eps Cep ', 741, 617, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(125, 'HD213306,V=3.75,F5Ib-G2Ib,Del Cep ', 1030, 735, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(126, 'HD213306,V=3.75,F5Ib-G2Ib,Del Cep ', 1030, 735, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(127, 'HD213973,V=6.60,A9III,', 1408, 2260, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(128, 'HD217476,V=5.00,G40,', 1558, 455, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(129, 'HD217476,V=5.00,G40,', 1558, 455, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(130, 'HD218376,V=4.85,B0.5IV,1 Cas ', 1703, 784, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(131, 'HD219586,V=5.56,F0IV,', 1907, 2337, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(132, 'HD219586,V=5.56,F0IV,', 1907, 2337, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(133, 'HD220369,V=5.56,K3II,', 1979, 872, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(134, 'HD220974,V=5.60,A6IV,', 2035, 2261, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(135, 'HD221253,V=4.91,B3IV,', 2106, 656, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(136, 'HD223128,V=5.95,B2IV,', 2301, 1792, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(137, 'HD224014,V=4.54,G20e,Rho Cas ', 2558, 548, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c');
INSERT INTO `stars` (`id`, `nombre`, `x`, `y`, `size`, `idConstellation`, `starDate`, `info`) VALUES
(138, 'HD224014,V=4.54,G20e,Rho Cas ', 2558, 550, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(139, 'HD224355,V=5.55,F1/6V+F3,', 2639, 312, 10, NULL, '2020-09-13', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c'),
(140, 'HD224355,V=5.55,F1/6V+F3,', 2639, 312, 10, NULL, '2020-10-03', ' HJD / Heliocentric Julian Date at start of exposure : 2459105.667279<br> FLUX / Signal extracted from image per second [ADU/s] : 3264.781<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 10.29<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.79<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.600785<br> FLUX / Signal extracted from image per second [ADU/s] : 1226.393<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 4.81<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.14<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008938<br> FLUX / Signal extracted from image per second [ADU/s] : 921.893<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 8.22<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.55<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.601254<br> FLUX / Signal extracted from image per second [ADU/s] : 741.687<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 22.61<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 7.95<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.138570<br> FLUX / Signal extracted from image per second [ADU/s] : 986.201<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 30.18<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 16.08<br> HJD / Heliocentric Julian Date at start of exposure : 2459105.666802<br> FLUX / Signal extracted from image per second [ADU/s] : 14375.696<br> XCEN / Profile centre of gravity with respect to raster origin [pixel] : 9.03<br> YCEN / Profile centre of gravity with respect to raster origin [pixel] : 12.57<br> HJD / Heliocentric Julian Date at start of exposure : 2459126.008877<br> FLUX / Signal extracted from image per second [ADU/s] : 1958.286<br> XCEN / Profile c');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `constellations`
--
ALTER TABLE `constellations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `stars`
--
ALTER TABLE `stars`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `constellations`
--
ALTER TABLE `constellations`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `stars`
--
ALTER TABLE `stars`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=141;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
